@startuml
skinparam maxMessageSize 200
autonumber "<b>[##]"
mainframe **sd** Заказ товара (часть)

actor Клиент as client
control "Система\nмаршрутизации" as route
control OMS as oms
entity Заказ as order
control "Колл-центр" as call
control WMS as wms

client++
client -> oms++ : Оформить заказ()

oms -> order++ : Создать заказ()
order --> oms : Заказ (статус = **СОЗДАН**)

== Получение остатков ==

oms -> wms++ : Получить остатки()
wms -> wms : Проверяет наличие остатков
|||
alt #HoneyDew Остатков достаточно
    wms --> oms : Остатков достаточно
    |||
else #MistyRose Остатков недостаточно
    wms --> oms-- : Остатков недостаточно
    oms -> call++ : Отправить данные по заказу и остаткам()
    ...Менеджер озванивается с клиентом для принятия решения о заказе...
    alt #white Скорректировать заказ
        call -> oms : Изменить состав заказа()
        oms -> order : Изменить заказ()
        order --> oms : Измененный заказ
    |||
    else #white Удалить заказ
        call -> oms-- : Удалить заказ()
        oms -> order : Отменить заказ()
        order --> oms : Заказ (статус = **ОТМЕНЕН**)
        note over oms, call : Завершение сценария
        |||
    end
    |||
end

== Оплата заказа ==

oms -> order : Изменить статус заказа()
order --> oms : Заказ (статус = **ОЖИДАЕТ ОПЛАТЫ**)
oms -> client : Сообщить, что заказ можно оплатить
client -> client : Оплачивает заказ
client --> oms : Сообщить, что заказ оплачен
oms -> order : Изменить статус заказа()
order --> oms : Заказ (статус = **ПОДТВЕРЖДЕН**)

== Формирование маршрута ==
loop #aliceblue До тех пор, пока не будет сформирован маршрут
oms -> route++ : Отправить данные по заказу()
route -> route : Ожидает дату доставки
route -> oms : Изменить статус заказа()
oms -> order : Изменить статус заказа()
order --> oms : Заказ (статус = **В ОБРАБОТКЕ**)
route -> route : Формирует маршрут
|||
alt #MistyRose Не найден курьер И/ИЛИ ТС
    route -> oms : Изменить статус заказа()
    oms -> order : Изменить статус заказа()
    order --> oms : Заказ (статус = **НЕ НАЙДЕТ КУРЬЕР И/ИЛИ ТС**)
    oms -> client : Сообщить, что не найден курьер и/или ТС
    client -> oms : Изменить дату доставки()
    oms -> order : Изменить заказ()
    order --> oms : Заказ (новая дата доставки, статус = **ПОДТВЕРЖДЕН**)
    oms -> client : Сообщить, дата доставки заказа изменена
|||
else #HoneyDew Маршрут сформирован
    route -> oms-- : Изменить статус заказа()
    oms -> order : Изменить статус заказа()
    order --> oms-- : Заказ (статус = **МАРШРУТ СФОРМИРОВАН**)
    oms -> client-- : Сообщить, что заказ скоро будет передан в доставку
    client--
    note over client, order: Завершение сценария
    |||
end
|||
end
@enduml
